// Generated by CoffeeScript 1.12.6
(function() {
  var _, async, csv, fork, fs, loopback, path;

  _ = require('lodash');

  async = require('async');

  csv = require('fast-csv');

  fork = require('child_process').fork;

  fs = require('fs');

  path = require('path');

  loopback = require('loopback');

  module.exports = function(Invoice) {
    Invoice.remoteMethod('upload', {
      accepts: [
        {
          arg: 'req',
          type: 'object',
          http: {
            source: 'req'
          }
        }
      ],
      http: {
        verb: 'post',
        path: '/upload'
      }
    });
    Invoice.import_handleLine = function(ctx, line, uploadData) {
      return this.import_validateLine(line).then((function(_this) {
        return function() {
          return _this.createInvoice(ctx, line);
        };
      })(this));
    };
    return Invoice.createInvoice = function(ctx, line) {
      return Invoice.findOne({
        where: {
          invoiceId: line.InvoiceId
        }
      }, ctx).then(function(found) {
        var invoice;
        invoice = {
          invoiceId: line.InvoiceId,
          amount: line.Amount
        };
        if (found) {
          //invoice.id = invoice.id;
          return 1;
        }
        return Invoice.upsert(invoice, ctx);
      });
    };
  };

}).call(this);
