// Generated by CoffeeScript 1.12.6
(function() {
  var err, options, server;

  server = require('../server.js');

  options = JSON.parse(process.argv[2]);

  try {
    server.models[options.model]["import"](options.container, options.file, options, function(err) {
      if (err) {
        console.error(err);
      }
      return process.exit(err ? 1 : 0);
    });
  } catch (error) {
    err = error;
    console.error(err);
    process.exit(err ? 1 : 0);
  }

}).call(this);
